### ISSUE TITLE
For the external reviewer

### ISSUE THREAD

**Issue by Braingenius2** [Braingenius2/space-travelers-hub#25]
Link to our project:  https://github.com/Braingenius2/space-travelers-hub/projects/1

We are a 3-member team including @Luffytaro22,  @Braingenius2  and @PedroH-Neves

**Comment by abdulhamiid** [comment]
# Status: Required Changes :recycle:
Hi Team 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Setup Kanban board 

## Required Changes ♻️
_Please kindly check the comments under the review._

![image](https://github.com/Braingenius2/space-travelers-hub/assets/78251927/ec4c4a84-4652-4bff-a356-40f2cac324ce)

I noticed that team member 3 is not assigned any task, please, let's ensure that all cards are assigned to team members. 🤗

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DuaneDave** [comment]
Hi @team 👋, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
